version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    networks:
      - default
    ports:
      - 8084:80
    volumes:
      - .m2:/root/.m2

networks:
  default:
    external:
      name: local-environment
