apiVersion: v1
kind: Service
metadata:
  name: evaluations-lb-qa
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
  selector:
    role: evaluations-qa
  type: LoadBalancer
  loadBalancerIP: "34.135.17.40"