apiVersion: v1
kind: Service
metadata:
  name: evaluations-lb
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
  selector:
    role: evaluations
  type: LoadBalancer
  loadBalancerIP: "34.72.46.9"